### ISSUE TITLE
 Error: webpack returned errors to ember-auto-import

### ISSUE THREAD

**Issue by tundak** [nano-wallet-company/nano-wallet-desktop#94]
```
VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.33.0
  - node: 10.11.0
  - openssl: 1.1.0i
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.0
  - v8: 6.8.275.32-node.28
  - zlib: 1.2.11

```

ERROR Summary:
```

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at webpack.run (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/ember-auto-import/js/webpack.js:161:32)
    at finalCallback (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:263:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/webpack/lib/Compiler.js:358:27)
    at /home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/neo-async/async.js:2830:7
    at done (/home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/neo-async/async.js:2865:11)
    at /home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/neo-async/async.js:2818:7
    at /home/tundak/Projects/sohantest/nano-wallet-desktop/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)

```
